### ISSUE TITLE
Why an extra setup action?

### ISSUE THREAD

**Issue by LinqLover** [hpi-swa/run-smalltalkci#9]
Sorry for spamming. I wonder whether it is necessary to have an extra setup action, which does not seem to be the default solution. Asking for curiosity only: What's the reason you decided to build an extra setup action instead of a smalltalkCI action itself? Wouldn't the latter make it easier for GitHub to cache the action? :-)

**Comment by LinqLover** [comment]
Hm, I just found another use case for using an extra setup action, if the single steps could be redistributed between the setup and the test task.

For my project, I use the [turnstyle action](https://github.com/marketplace/actions/action-turnstyle) to ensure some tests that access a global web service are not executed at the same time. So I run this action right before my turnstyle action:

```yml
name: smalltalkCI

on: [push, pull_request]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: Squeak64-Trunk
      - name: Turnstyle (critical section)
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run test suite
        run: smalltalkci -s ${{ matrix.smalltalk }}
```
However, this leads to unnecessarily long delay times after the first `smalltalkci` job instance has run (e.g. for the push) **because the second job instance does not start to prepare the Squeak image before the first job instance has quitted.** I could speed up my Actions workflow if this critical section could be reduced by breaking the `smalltalk` ci job down into separate jobs for setup + testing.

What do you think? Would this be far too complex? :-) Also, if we can use better caching as described in hpi-swa/smalltalkCI#471, the steps described here would become redundant.
